# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  TestFlight.takeOff('a0d19689d60be388f0d1eae92edc80a8_MTMxMTUzMjAxMi0wOS0xMiAwMjowMzoyMS45MTE1NzU')
  end)
end
